/users
  get: #~15|spike了很久，几个小时吧
    reponse:
      200:
        body:
          application/json:
            type: object[]
              uri: string
              id: number
              name: string
  post: #~15 | 创建成功 10:07
    body:
      application/x-www-form-urlencoded:
        formParams:
          name: string
    reponse:
      200:
        body:
          application/json:
            type: object
              uri: string
              id: number
              name: string
  /{user-id}
    get: #~10| 13:17 还是请求太简单，请求要复杂了，就不好办了
      response:
        200:
          body:
            application/json:
              type: object
                uri: string
                id: string
                name: string
    /expense-requests
      get: #~15|44:43 级联不熟
        response:
          200:
            body:
              application/json:
                type: object[]
                  uri: string
                  requester: object
                    uri: string
                    name: string
                  approver: object
                    uri: string
                    name: string
                  amount: number
                  requestDate: date
      post: #~15|19:44 requester 其他属性没显示
        body:
          application/x-www-form-urlencoded:
            formParams:
              name: string
        response:
          200:
            body:
              application/json:
                type: object
                  uri: string
                  requester: object
                    uri: string
                    name: string
                  amount: number
                  name: string
      /{expense-request-id}
        get: #~10|9:17 很多细节数据没有取 54:42: 细节数据也处理完毕，不一致的行为造成了很多的浪费，忘记怎么从bson中取id浪费了很多时间，抽取从bson和document中获取id的方法花了一些时间
          response:
            200:
              body:
                application/json:
                  type: object
                    uri: string
                    requester: object
                      uri: string
                      name: string
                    approver: object
                      uri: string
                      name: string
                    amount: number
                    status: string
                    dateRequested: date
                    dateApproved: date
        put: #~10| 32:51因为忘记了级联对象只能设置id，结果浪费了半小时，38:06 204不熟，结果浪费了一些时间
          body:
            application/x-www-form-urlencoded:
              formParams:
                name: string
                approverId: string
                status: string
          response:
            200:
              body:
                application/json:
                  type: object
                    uri: string
                    requester: object
                      uri: string
                      name: string
                    approver: object
                      uri: string
                      name: string
                    amount: number
                    status: string
                    dateRequested: date
                    dateApproved: date
        /expense-items
          get: #~15|38:44: 准备好before,it class：16:07，发现controller应该改成request: 3:00 级联&处理各种错误: 7:44
            response:
              200:
                body:
                  application/json:
                    type: object[]
                      uri: string
                      amount: number
                      consumeDate: date
                      category: object
                        uri: string
                        name: string
                      comment: string

          post: #~15|22:36 写测试和实现 12:22, 做到一半做晕了，脑子犯晕，意识不到该找哪些数据：8:00， 剩下时间修bug，发觉find的时候()写成了[]
            body:
              application/x-www-form-urlencoded:
                formParams:
                  amount: number
                  categoryId: string
                  comment: string
            response:
              200:
                body:
                  application/json:
                    type: object
                      uri: string
                      amount: number
                      category: object
                        uri: string
                        name: string
                      comment: string
          /{expense-items-id}
            get: #~10
              response:
                200:
                  body:
                    application/json:
                      type: object
                        uri: string
                        amount: number
                        category: object
                          uri: string
                          name: string
                        comment: string
            put: #~10
              body:
                application/x-www-form-urlencoded:
                  formParams:
                    amount: number
                    categoryId: string
                    comment: string
              response:
                200:
                  body:
                    application/json:
                      type: object
                        uri: string
                        amount: number
                        category: object
                          uri: string
                          name: string
                        comment: string
        /payment
          get: #~15
            response:
              200:
                body:
                  application/json:
                    type: object
                      uri: string
                      account: string
                      amount: number
          post: #~15
            body:
              application/x-www-form-urlencoded:
                formParams:
                  account: string
            response:
              200:
                body:
                  application/json:
                    type: object
                      uri: string
                      account: string
                      amount: number

/expense-item-categories
  get: #~15
    resposne:
      200:
        body:
          application/json:
            type: object[]
              uri: string
              name: string
  post: #~15
    body:
      application/x-www-form-urlencoded:
        formParams:
          name: string
    resposne:
      200:
        body:
          application/json:
            type: object
              uri: string
              id: string
              name: string
  /{expense-item-category-id}
      get: #~10
        resposne:
          200:
            body:
              application/json:
                type: object
                  uri: string
                  name: string
      put: #~10
        body:
          application/x-www-form-urlencoded:
            formParams:
              name: string
        response:
          200:
            body:
              application/json:
                type: object
                  uri: string
                  name: string
    /policies
        get: #~15
          response:
            200:
              body:
                application/json:
                  type: object[]
                    uri: string
                    name: string
        post: #~15
          body:
            application/x-www-form-urlencoded:
              formParams:
                name: string
                rules: object[]
          response:
            200:
              body:
                application/json:
                  type: object
                    uri: string
                    name: string
                    rules: object[]
                    publishDate: date
                    dueDate: date
      /{policy-id}
        get: #~10
          response:
            200:
              body:
                application/json:
                  type: object
                    uri: string
                    name: string
                    rules: object[]
                    publishDate: date
                    dueDate: date
        put: #~10
          body:
            application/x-www-form-urlencoded:
              formParams:
                name: string
                rules: object[]
                dueDate: date
          response:
            200:
              body:
                application/json:
                  type: object
                    uri: string
                    name: string
                    rules: object[]
                    publishDate: date
                    dueDate: date
      /current
        get: #~10
          response:
            200:
              body:
                application/json:
                  type: object
                    uri: string
                    name: string
                    rules: object[]

      